name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday
  SERVICE_ACCOUNT: fooServiceAcct
  SERVICE_PASSWORD: fooServiceAcctPwd

jobs:
  
  greeting_job:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name $SERVICE_ACCOUNT owner. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          framework: sca_package
          output: JSON
          soft-fail: on
      
