name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday
  SERVICE_ACCOUNT: fooServiceAcct
  SERVICE_PASSWORD: fooServiceAcctPwd

jobs:
  
  build_job:
    runs-on: [self-hosted, Linux, X64]
    permissions: 
      contents: read
      packages: write
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name $SERVICE_ACCOUNT owner. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          framework: sca_package
          output_format: cyclonedx
          output_file_path: sbom
          soft_fail_on: MEDIUM
          hard_fail_on: CRITICAL
          skip_download: --skip-download
          skip_check: CRITICAL

      - name: Create file status_build.txt and write the job status into it
        if: always()
        run: |
          echo ${{ job.status }} > status_build.txt

      - name: Upload file status_build.txt as an artifact
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: pass_status_build
          path: status_build.txt
  
      - name: Upload SBOM results file as an artifact
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: pass_sbom_results
          path: sbom/results_cyclonedx.xml

  archive-build:
    needs: [build_job]
    if: always()
    name: Archive
    runs-on:
      labels: [self-hosted, Linux, X64]

    steps:
      - name: Download artifact pass_status_build
        uses: actions/download-artifact@v1
        with:
          name: pass_status_build

      - name: Download artifact pass_sbom_results
        uses: actions/download-artifact@v1
        with:
          name: pass_sbom_results

      - name: Set the statuses of build as output parameters
        id: set_outputs
        run: |
          echo "::set-output name=status_build::$(<pass_status_build/status_build.txt)"
          echo "::set-output name=sbom_results::$(<pass_sbom_results/results_cyclonedx.xml)"

